"""add owner to monitoring objects

Revision ID: 7e330d8fe350
Revises: 7006160b3df6
Create Date: 2026-08-24 23:46:17.233246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e330d8fe350'
down_revision: Union[str, Sequence[str], None] = '7006160b3df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_objects', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_monitoring_objects_owner_id'), 'monitoring_objects', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'monitoring_objects', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitoring_objects', type_='foreignkey')
    op.drop_index(op.f('ix_monitoring_objects_owner_id'), table_name='monitoring_objects')
    op.drop_column('monitoring_objects', 'owner_id')
    # ### end Alembic commands ###
